### ISSUE TITLE
4/8分科会ニュースを作成する。

### ISSUE THREAD

**Issue by ta-hisa** [Code4Yokohama/code4yokohama.github.io#111]
（テキスト案）
2021.4.8　分科会「urbanmanagement」定例会
年度最初の定例会では、2021年度の活動計画のブレストを行いました。定例会では、今年度は「技術駆動都市ヨコハマ」のアップデートや、公共施設マネジメントの提案など横浜市のデータにC4Yがスパイスを加え、色々な場所で、さらに活用・発展できるような流れを作りたいということなどを話し合いました。
そして、Code for Japan summitでグラレコ隊として活動していたフレッシュな新メンバーがC4Yに初参加！
定例会の内容を素敵なグラレコで記録してくれました。

**Comment by ta-hisa** [comment]
> （テキスト案）
> 2021.4.8　分科会「urbanmanagement」4月定例会
> 定例会では活動計画のブレストを行いました。今年度は、「技術駆動都市ヨコハマ」のアップデートや、公共施設マネジメントの提案など横浜市のデータにC4Yがスパイスを加え、色々な場所で、さらに活用・発展できるような流れを作りたいというビジョンを共有しました。
> そして、今回からCode for Japan summitでグラレコ隊として活動していたフレッシュな新メンバーがC4Yに初参加！
> 定例会の内容を素敵なグラレコで記録してくれました。

**Comment by iwao** [comment]
公開した
