### ISSUE TITLE
トップページのタイトルがJekyllのまま

### ISSUE THREAD

**Issue by hirokiu** [Code4Yokohama/code4yokohama.github.io#140]
`<title>Code for YOKOHAMA | App marketing template for Jekyll.</title>`

![Screen Shot 2021-05-10 at 20 21 29](https://user-images.githubusercontent.com/2187843/117652045-a59eec80-b1cd-11eb-92bb-e45deb8efd9b.png)

**Comment by iwao** [comment]
なおしたー
