### ISSUE TITLE
OGPとかfaviconとか調整

### ISSUE THREAD

**Issue by iwao** [Code4Yokohama/code4yokohama.github.io#15]
画像つくって対応する。

**Comment by Rindrics** [comment]
Open Graph Protocol
デフォルトのテンプレートの中にOGPを追加する

**Comment by Rindrics** [comment]
https://mukai-lab.info/pages/tech/jekyll/2016-02-23-ogp/

**Comment by Rindrics** [comment]
>"_includes/head.html"に下記のように page.image を利用してOGPの設定をします．

**Comment by Rindrics** [comment]
違うディレクトリをいじってしまったみたい。
いったん違う情報をあたってみる。
次は https://takezoe.hatenablog.com/entry/2016/07/03/104536 。
https://github.com/jekyll/jekyll-seo-tag を使う方法らしい

**Comment by Rindrics** [comment]
jekyll-seo-tag、すでに入ってました
