### ISSUE TITLE
【プロジェクト紹介ページ作成】里山ガーデン映像コンテスト

### ISSUE THREAD

**Issue by iwao** [Code4Yokohama/code4yokohama.github.io#54]
つくる。
ちなみに、コンテストページの移植については別にissueがたっている。

**Comment by iwao** [comment]
シンプルだけれど、用意した。あと、コンテストページの移設が終わったろころでリンクはる。（別途issue立てた）

**Comment by nichesuch** [comment]
作ってある
https://code4yokohama.github.io/projects/satoyama/
