### ISSUE TITLE
メンバー紹介の飛び先ページの設定

### ISSUE THREAD

**Issue by ocean3fish** [Code4Yokohama/code4yokohama.github.io#60]
/aboutのMembersの各メンバーの名前をクリックした時に、コンテンツがあれば詳細ページに飛ぶようにする。

**Comment by nichesuch** [comment]
今はtwitter_urlにリンクを貼っていて、デフォルトだと`/about/`に飛ぶようです。
コンテンツはそこまで多くないので、詳細ページではなく、全部表示。
リンクは各ソーシャルボタンを作る。
