### ISSUE TITLE
メンバーの表示順

### ISSUE THREAD

**Issue by ocean3fish** [Code4Yokohama/code4yokohama.github.io#63]
/aboutのMembersの各メンバーの並び順が現在アルファベット順になっている模様。
表示順を制御できるようにしたい。

**Comment by nichesuch** [comment]
表示順はアルファベット順のままにして、コアメンバーとアクティブメンバーに分けるようにする。

**Comment by iwao** [comment]
できてるみたいなのでクローズ！
