### ISSUE TITLE
問い合わせフォーム、問い合わせの行方

### ISSUE THREAD

**Issue by iwao** [Code4Yokohama/code4yokohama.github.io#74]
POSTの送り先がこれらしいのだが、これがちゃんと動くか確認しつつ、誰がどのように受信できるかも確認する。
https://formspree.io/xgepwwbn

**Comment by MasaGon** [comment]
確認済みです。僕がアカウント持ってます。

**Comment by MasaGon** [comment]
Slackにも飛んでるはず。
![image](https://user-images.githubusercontent.com/3581778/104731241-c656b880-577e-11eb-893f-c826551e45c5.png)

**Comment by iwao** [comment]
きてるね。クローズ！

**Comment by MasaGon** [comment]
プランはこれ。月間50通まで。
![image](https://user-images.githubusercontent.com/3581778/104731505-22b9d800-577f-11eb-82e8-b53842838b7b.png)
