### ISSUE TITLE
トップページだけ上部のグラデーションが濃い

### ISSUE THREAD

**Issue by ocean3fish** [Code4Yokohama/code4yokohama.github.io#79]
トップページ
<img width="1440" alt="スクリーンショット 2021-01-15 23 44 19" src="https://user-images.githubusercontent.com/4206675/104741012-fc4e6980-578b-11eb-9da8-4946e54852ba.png">

/projects
<img width="1440" alt="スクリーンショット 2021-01-15 23 44 27" src="https://user-images.githubusercontent.com/4206675/104741058-0c664900-578c-11eb-9621-fa6d419c7b36.png">

**Comment by hirokiu** [comment]
理由が不明だが，トップのナビゲーションバーの分だけずれている模様．
最初の読み込みで，ナビゲーションバーがない状態でHTMLをレンダリングしているようにみえる．
