### ISSUE TITLE
トップページの "Join Now" クリック後にワンクッション説明ページをはさみたい

### ISSUE THREAD

**Issue by ocean3fish** [Code4Yokohama/code4yokohama.github.io#8]
現状：すぐSlackの登録フォームに飛ぶ
https://join.slack.com/t/code4yokohama/shared_invite/zt-e63peaf8-AIxGiecu5IgR2DHAiv~c~g

問題点：初見の人はビックリしそう

変更案：「C4Yにご参加いただくには〜」的な簡単な説明と手順を書いたページに遷移するようにして、そこからSlackのフォームへうまく誘導できるようにする

**Comment by iwao** [comment]
aboutページを充実させつつ、まず、aboutページに誘導してはどうか。

**Comment by iwao** [comment]
about ページにリンクすることにしたのでクローズ！
