### ISSUE TITLE
OGP画像の設定が必要

### ISSUE THREAD

**Issue by ocean3fish** [Code4Yokohama/code4yokohama.github.io#81]
デフォルトの画像が出てしまうのでOGP画像の設定が必要

**Comment by hirokiu** [comment]
OGP画像は，mdファイル上部に記載された image と連動しているので，出し分けが必要ということでしょうか？
トップページなども同様ですね．

**Comment by hirokiu** [comment]
現状は、image: に設定してある画像がogpに設定されています。
問題なければcloseしてください。
