### ISSUE TITLE
サービスデザインワークショップのプロジェクト作成

### ISSUE THREAD

**Issue by t09252fk** [Code4Yokohama/code4yokohama.github.io#84]

**Comment by ta-hisa** [comment]
サービスデザインワークショップ紹介文案
※加藤さんに確認する
行政サービスに対する市民の満足度や業務効率化に向けて「利用者」目線でアプローチする
サービスデザインの手法が有効とされています。そうした中、横浜市職員有志勉強会「よこはまY Yラボ」のメンバーを行ったお悩み相談会で、「サービスデザインに対する理解度を上げたい」という相談を受け、「Code for YOKOHAMA×よこはまY Yラボ」のコラボで、「サービスデザインワークショップ」プロジェクトが立ち上がりました。

**Comment by iwao** [comment]
ひとまず、追加した。
