### ISSUE TITLE
リスト表示が妙に行間空いている

### ISSUE THREAD

**Issue by iwao** [Code4Yokohama/code4yokohama.github.io#87]
![スクリーンショット 2021-04-21 19 13 57](https://user-images.githubusercontent.com/622349/115537390-bbf40f80-a2d5-11eb-85b9-532632d53503.png)
リスト表示が妙に行間空いている

**Comment by hirokiu** [comment]
ブログ一覧表示ページのCSSが原因

**Comment by hirokiu** [comment]
./_sass/blog.scss のliのpaaddingです．

```
.blog-posts {
	list-style: none;
	padding: 0;
	margin: 0;
	font-size: 1em;

	li {
		padding: 50px 0;
	}

	li {
		padding: 50px 0;
	}
```
